### ISSUE TITLE
DeepPipe Paper Dataset

### ISSUE THREAD

**Issue by fatemechangizian** [ZENULI/PyPipes#1]
Hi all,
I've recently noticed that you are working on implementing DeepPipe pipeline, just wanted to inform you that you can also find the original dataset of the paper here,
https://github.com/wzsdu/DeepPipes_Dataset

There is also another thing that I would like to ask, I am working on a 3D classification as my semester project and as it is really close to what I am trying to do, I believe it would be great for me if I could reimplement the paper method code up until the classification part which is the pointCNN algorithm. But unfortunately, it seems the repository isn't complete yet, therefore I am wondering if you could share the notebook up until the classification part, however, I am not sure if it's already finished or not.

**Comment by nmellado** [comment]
Hi @fatemechangizian ,
This repository has been set by a group of students for a semester project. 
Unfortunately they couldn't finish the training part in time, but maybe they will spend some time to finish it ? 

@seb2s @BastienKovac @Ulynor do you plan to continue working on this project or not ?

**Comment by nmellado** [comment]
And thanks for the dataset link @fatemechangizian .

**Comment by seb2s** [comment]
We have just published the latest improvements to the project but the classification is not yet up and running.
There are indeed plans to complete the repository but probably not for this semester. However, you can still find some useful elements of our work in the 3D model generation and the database. 
Good luck with your project!

**Comment by Tomoki-0526** [comment]
@fatemechangizian @nmellado Hello, I’m working on this dataset but don't get a good result. The points belong to 0-pipe is much more than other classes, so my network only predict '0'. Have you encountered the same problem?
